### ISSUE TITLE
Releasing geo api integration

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1534]
This ticket will outline all next steps to merge and release geo API integration. All of this work is currently happening in #1514. The API changes are merged to go-api staging.

## Data
* [x] **Update bbox and centroid for all countries** — includes importing [right centroid](https://github.com/IFRCGo/go-frontend/issues/1532), and manually or semi-manually updating countries in the database we can't find a match in ICRC shapefile [listed here](https://github.com/IFRCGo/go-frontend/issues/1464). — @jhenshall @geohacker 
* [x] **Update bbox and centroid for all districts** — for this, we need to match the [missing districts listed here](https://github.com/IFRCGo/go-frontend/issues/1473). — @jhenshall @geohacker 
* [x] **Update iso3 codes for all countries** — [ticket](https://github.com/IFRCGo/go-frontend/issues/1522) — @jhenshall @geohacker 
* [x] **Fix new Nepal districts** — [ticket](https://github.com/IFRCGo/go-frontend/issues/1422) — @jhenshall
* [x] **Update independence status for all countries** — in the ICRC shapefile, there's a column called `independent`, we can use this field along with other logic to filter for countries in the field report form. — @jhenshall
* [x]  ~~**Fix country names** — the ICRC shapefile has names in a sometimes weird format. For example: https://ifrc-go-feature-geo-apis.surge.sh/countries/25#operations `Bahamas, The` — @jhenshall~~
* [x] **Add names to regions** — add column in the regions table for name, that can be used in the front-end. So we can have the right name for https://ifrc-go-feature-geo-apis.surge.sh/regions/4#operations — @geohacker

@jhenshall a lot of these need your support. Instead of waiting to generate canonical shapefile for us to run the import, I suggest we run through the missing countries and districts and prepare a 'temporary' shapefile that has the right names, iso3 codes etc. That we can get through all the above relatively fast. Let me know what you think!

## Testing
* [x] Functionality testing — happening at https://github.com/IFRCGo/go-frontend/issues/1531
* [x] Business logic — since we move away from front-end hardcoded values, this requires a bunch of careful testing across the board. Checking new reports, existing reports, existing country -> district associations, country list dropdowns etc.

cc @batpad @nanometrenat @LukeCaley @teklal

**Comment by nanometrenat** [comment]
Not been involved in this but just one thing to note:

> * [ ]   **Fix country names** — the ICRC shapefile has names in a sometimes weird format. For example: https://ifrc-go-feature-geo-apis.surge.sh/countries/25#operations `Bahamas, The` — @jhenshall
I believe this format is deliberate, to allow alphabetising.  NOTE that changing name format away from what it currently is on GO would need careful consideration and may not be something for this round.  Other systems have exports/displays with current format so may also need renaming if renaming on GO (e.g. surge db).
But agree that somehow being able to have countries appear in the alpha order we want while also having them being in formats that are recognisable by automatic geocoding (e.g. in Tableau and PBI) would be an amazing end state.  Also bearing in mind the country names as per Governance files - i.e. shouldn't be changed lightly!

**Comment by jhenshall** [comment]
Hey @geohacker - all of this looks to be covered now except the 'update independence status for all countries'. Can't find a ticket specifically on this. Do you have an update? Would also be great to filter countries in the dropdown based on independence if possible ([also mentioned here](https://github.com/IFRCGo/go-frontend/issues/1276#issuecomment-682074269)).

**Comment by geohacker** [comment]
@jhenshall I think our plan now is to not edit that bit and leave the API as is. We should fill this in once the new shapefile with all data inconsistencies are resolved. So for now, users can expect what they have always seen and it doesn't break anything. Does that sound ok?

**Comment by geohacker** [comment]
Now that we have done all the above things that involve code and data changes and deployed them to staging, I'll outline the steps to take when we go to production.

All the data files are in a dropbox folder which Johnny, Greg and I have access to at the moment. If anyone else need access, please let me know.

## regions
* [ ] Update bbox by running `python manage.py update-region-bbox`

## admin0
* [ ] First generate a list of missing countries by running `python manage.py import-admin0-data admin0.shp`
* [ ] Inspect the missing-countries.txt file and share with Johnny and Sajjad
* [ ] Then import bbox, centroid, iso3, and independence status for countries by running `python manage.py import-admin0-data admin0.shp --update-bbox --update-centroid country-centroids.csv --update-iso3 iso2-iso3.csv --update-independent`

## admin1
* [ ] Generate a list of missing districts by running `python manage.py import-admin1-data admin1.shp`
* [ ] Inspect the missing-districts.txt file and share with Johnny and Sajjad
* [ ] Import bbox, centroid from the admin1.shp by running `python manage.py import-admin1-data admin1.shp --update-bbox --update-centroid`
* [ ] Then import missing Nepalese districts by running:
   * `python manage.py import-admin1-data --import-all  20200826_NepalRC_Nepal-adm1/20200826_NepalRC_Nepal-adm1.shp`
  * `python manage.py import-admin1-data --import-missing missing-districts.txt  20200826_NepalRC_Nepal-adm1/20200826_NepalRC_Nepal-adm1.shp`
* [ ] Johnny to deprecate old Nepalese districts not used anymore by using the deprecate flag.
* [ ] Then import other missing districts by running:
  *  `python manage.py import-admin1-data go-missing-districts-aug-28-2020/go-missing-districts-august-28-2020.shp`
  * `python manage.py import-admin1-data --import-missing missing-districts.txt  go-missing-districts-aug-28-2020/go-missing-districts-august-28-2020.shp`

cc @GregoryHorvath @jhenshall @batpad

**Comment by jhenshall** [comment]
@geohacker - only just managed to test the 3W form after the dropdown issues. Would be great to have the dropdowns on 3W forms follow the same logic as field reports to exclude `independence`=`false`. Understand this wasn't clear, so if it's a quick, low-risk change, great, otherwise, we'll come back to it after release. Cheers.

**Comment by batpad** [comment]
@jhenshall can you confirm that the 3w form now shows only independent countries?

**Comment by jhenshall** [comment]
@batpad - Yes, confirmation it's working as expected now! Thanks @geohacker for the late fix. 😄

**Comment by batpad** [comment]
Moved this to `Ready for UAT` - @jhenshall - if you can confirm that all these steps are done and the geo-data on prod looks fine, we can move this to Done and Close. Thanks!

**Comment by jhenshall** [comment]
Created a new ticket for the issue for the weird formatting of country names that use commas. Apart from that all good @batpad !
