### ISSUE TITLE
Enhance geospatial data handling - Phase 4.4

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1643]
## Issue
This is a master ticket for issues related to geo data that will be covered by the wider geospatial review as part of phase 4.4. This brings some outstanding issues from #938 as well as new issues created since then.

The key steps for this piece of work are:
1. Map out existing data model of geo data and how elements are related
2. Starting from ICRC shapefiles, create a 'source of truth' shapefile with all attributes wanted on GO database
3. Get sign off, especially for:
 a. Country names
 b. Overseas territories
 c. Disputed territories
 d. Handling of cluster and region offices
4. Map out how to implement these changes and the impact on related elements highlighted in step 1

This is just the planning stage and does not yet consider the implementation and significant testing that will be required!

## Related issues
- #1464 
- #1523 
- #1623 
- #1672
- #1684 

cc @geohacker @batpad @LukeCaley @tovari

**Comment by jhenshall** [comment]
Outlining the steps to be made for this round of geo changes. Will continue to edit this comment to make sure accurate and @geohacker, please do check and feel free to edit too. 🙂 

## Changes in Django admin
To be done by @jhenshall 
- [ ] #1684 Match clusters to current organisation structure
- [ ] #1623 Change country names to those agreed by governance (pending sign off)

## Schema changes
To be done by @geohacker 
- [ ] #1464 Add missing countries - @jhenshall to provide shapefile with only these countries
- [ ] #1690 Link non-independent nations to the 'sovereign state' - @jhenshall to provide CSV: `country GO ID` > `sovereign state GO ID`)
- [ ] #1681 Uppercase ISO codes
- [ ] #1689 Link NS countries to cluster - @jhenshall to provide CSV: `country GO ID` > `cluster GO ID`
- [ ] #1672 Appeal ingest geographical mapping with @GregoryHorvath - @jhenshall to provide CSV: `GEC codes` > `country ISO`

cc @batpad

**Comment by geohacker** [comment]
@jhenshall this list looks great to me!

**Comment by geohacker** [comment]
@jhenshall this list looks great to me!

**Comment by jhenshall** [comment]
Some changes were made on prod but others were left to be made on staging and allow for more testing. Those outstanding are:

- [ ] #1623 Get final sign off and make the country name changes
- [ ] #1464 Add missing countries
- [ ] #1690 Link non-independent nations to the 'sovereign state'
- [ ] #1672 Appeal ingest geographical mapping
- [ ] #1785 Prepare additional layers for the tileset - disputed boundaries and tilesets

Once these are finalised, hopefully all the data will be ready for the accurate tileset generation. Styling and implementation then part of next phase.

@geohacker hopefully this captures all?

**Comment by geohacker** [comment]
@jhenshall that list captures everything, thank you!

**Comment by jhenshall** [comment]
Hey @geohacker @GregoryHorvath, great to have the countries in! Done some initial testing (more just clicking around than systematic at this point) and capturing a few points here. 

### Admin site
- Disputed status is added to `Society name [en]` and the `disputed` checkbox is not checked - e.g. [Hala'ib triangle](https://dsgocdnapi.azureedge.net/en/api/country/349/change/)
- Sovereign state not filled in - e.g. [Isle of Man should be UK](https://dsgocdnapi.azureedge.net/en/api/country/331/change/)
- Centroid and bbox are empty - I actually think this is ok but noting for discussion

### Frontend
Realise that some of these were probably already there but adding multiple new non-independent countries has exaggerated it.
- [Adding a 3W entry](https://dsgoproxyapp.azurewebsites.net/regions/0#3w): `Reporting National Society` - some National Societies are listed multiple times. Perhaps only showing entries where `independent` = `TRUE` will solve this as only the sovereign state (and their NS) will be shown?
- On [region pages](https://dsgoproxyapp.azurewebsites.net/regions/0), the `All countries` list that slides in from the right - can this only show `independent` = `TRUE`?

### Search
As discussed, the current method of restricting elastic search to `National Society`=`NULL` doesn't work. If we stick to existing fields, I would propose only showing countries where:
- `record_type`=`1`
- `independent`=`TRUE`
- `deprecated`=`FALSE`

But, also happy to have a new `in_search` field or something - this could actually be used for more than just search - for all lists where we want to focus the results.

Hope that all makes sense. Would be good to chat through some of these.

cc @batpad @tovari

**Comment by GregoryHorvath** [comment]
@jhenshall Added the `in_search` field and actually there was an issue with the implementation of the handling of the indices for Countries for Elasticsearch, so also fixed that. These are deployed to staging.

The `in_search` field is defaulted to `True`, so all `Country` records picked it up (including those ominous region-country-region records). cc @geohacker @batpad

**Comment by jhenshall** [comment]
Compiling a final checklist of things to be done for the prod release, hopefully early next week. As always, let me know if anything not as expected @geohacker @batpad @GregoryHorvath .

### Management commands on prod
@GregoryHorvath @geohacker 


- [ ] #1464 Add missing countries
- [ ] #1473 Add missing districts
- [ ] #1709 Update geometries for disputed territories
- [ ] #1690 Link non-independent nations to the 'sovereign state'
- [ ] Update disputed status?


### Frontend / code changes
@geohacker @batpad 
- [ ] #1672 Appeal ingest geographical mapping
- [ ] #1474 Mapbox tileset creation from prod data? When do we generate the TMS?

**Homepage map**

- [ ] #1835 Remove movement response from homepage map
- [ ] #1815 Add map attribution credits
- [ ] #1811 Change text on map legend and popup
- [ ] #1202 Change point colours as discussed in these comments

### Changes in Admin / Mapbox
@jhenshall 
- [ ] #1785 Add additional layers to Mapbox - disputed boundaries
- [ ] #1840 Remove ISO from clusters and regions
- [ ] #1445 Link existing districts to newly imported countries

cc @tovari

**Comment by geohacker** [comment]
> Centroid and bbox are empty - I actually think this is ok but noting for discussion

This is because the `--update-bbox` and `--update-centroid` flags are missing, but can be fixed in production when running the management command.

> - [Adding a 3W entry](https://dsgoproxyapp.azurewebsites.net/regions/0#3w): `Reporting National Society` - some National Societies are listed multiple times. Perhaps only showing entries where `independent` = `TRUE` will solve this as only the sovereign state (and their NS) will be shown?
> - On [region pages](https://dsgoproxyapp.azurewebsites.net/regions/0), the `All countries` list that slides in from the right - can this only show `independent` = `TRUE`?

@batpad could you take look and let me know what I should do here? I'm not entirely sure.

**Comment by batpad** [comment]
> Adding a 3W entry: Reporting National Society - some National Societies are listed multiple times. Perhaps only showing entries where independent = TRUE will solve this as only the sovereign state (and their NS) will be shown?

We seem to be applying the filter for independent here already, so it seems like there's something else going on here causing the duplicates.

We can look at this a bit more to figure out where this duplication is coming from.

@jhenshall do you have any idea if there are other reasons why NS names could be duplicated for different countries?

@frozenhelium may need your help to understand the data parsing for the 3w bits - would you be around for a quick chat to look at this?

**Comment by jhenshall** [comment]
@batpad I don't think the independent filter is working. To clarify this is for the top dropdown of 'Reporting National Society' drop down, not the second down of 'Country'.

The pattern of duplicate National Societies points towards overseas territories also being included as separate NS. e.g. UK and Montserrat both have British Red Cross as NS but are listed separately. Filtering by independent - would only show UK entry.

There are also lots of 'Disputed' NS  - which should not be shown... again independent filter should account for these.

**Comment by jhenshall** [comment]
@batpad @geohacker @tovari @GregoryHorvath - I've updated [this overview comment](https://github.com/IFRCGo/go-frontend/issues/1643#issuecomment-784946886) with blockers before launch. Hopefully we can get these done on Monday? Then testing ([outlined here](https://github.com/IFRCGo/go-frontend/issues/1858)) and release Wednesday? 🤞

**Comment by jhenshall** [comment]
This was a pretty epic ticket and all done except for the Mapbox build, which is currently blocked but all outlined in #1474. With just one outstanding ticket left, we can close this master ticket.

Thank you @geohacker @GregoryHorvath and @batpad for all the work on this! 🙌
