### ISSUE TITLE
3W improvements

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1819]
This is to collect all 3W related user stories in scope in 2021.

- [x] PNS view, Global views: https://github.com/IFRCGo/go-frontend/issues/1823

Other improvements:
- [x] 3w bulk upload feature is incorrectly importing date fields #1884
- [x] User roles: https://github.com/IFRCGo/go-frontend/issues/1312
- [x] Disaster type for Bilateral: https://github.com/IFRCGo/go-frontend/issues/1148
- [x] 3W email notifications https://github.com/IFRCGo/go-api/issues/1061
- [ ] Sankey info flow: https://github.com/IFRCGo/go-frontend/issues/1315
- [x] 3W API call - csv format: https://github.com/IFRCGo/go-api/issues/768

**Comment by SimonbJohnson** [comment]
#1822 could be facilitated via HXL.
