### ISSUE TITLE
DREF request

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1948]
The DREF request tool is a new form on GO to submit DREF appeal requests.
The form consists of many drop-down lists, free text or decimal value fields, date fields, radio buttons, upload  function for external maps and photos. It can be linked to an existing Field Report (through a FR selection box) that will prepopulate many fields already available in the Field Report. 
After the form submission, the application approval flow will start. ~~That means, that certain users will have specific permissions to approve these applications. This will involve multiple approvers. The form submitter user will be able to overview the ongoing and approved applications on a “My DREF applications” tab on the user account page.~~

Wireframes:
https://www.figma.com/proto/RZTZdDWf6Xjweh9GA8rMGW/IFRC_GO_Wires_20210502?page-id=0%3A72&node-id=832%3A0&viewport=3953%2C3106%2C0.10871457308530807&scaling=scale-down-width&hide-ui=1

Components:
1. DREF request form. - Form is described in the DREF application.xlsx document here: https://teams.microsoft.com/_#/files/General?groupId=a9de50a6-c405-49bd-aa85-d4534f7d6cf2&threadId=19%3A8f526fd5b918469799d2462ff2c5e1f0%40thread.skype&ctx=channel&context=DREF%2520tool&rootfolder=%252Fsites%252FGOIVfordeveloperteam%252FShared%2520Documents%252FGeneral%252FRequirement%2520documents%252FDREF%2520tool
Fields that can be populated from the linked Field Report are also described in the same document (Data mapping from Field Reports section)
2. Data tables
3. 'My DREF applications' overview page - Requirements TBA.

No data integration with other systems is planned at the moment,

TBA:
- [ ] approval flow, approval permissions

**Comment by tovari** [comment]
@frozenhelium, requirements may change a bit here and there, but the request form implementation and the related database updates could start based on the available document.

**Comment by frozenhelium** [comment]
CC: @thenav56 @suraj-ram-shrestha

**Comment by frozenhelium** [comment]
Very initial version available at
https://ifrc-go-add-dref-application.surge.sh/dref-application

@tovari  @marcovvu1

**Comment by marcovvu1** [comment]
Thanks! 

I went through it, it is looking good although of course some functionality is still missing of course. One thing I want to confirm is whether you ave the latest version of the tool, as some wording and sections will have to change in the preview based on the existing DREF application form @frozenhelium

Thanks! 

> Very initial version available at
> https://ifrc-go-add-dref-application.surge.sh/dref-application
> 
> @tovari @marcovvu1

**Comment by frozenhelium** [comment]
@marcovvu1 @tovari We've nearly completed the DREF from and have started the internal testing. The testing server is available at: https://ifrc-go-feature-dref.surge.sh/
We're still polishing some of the features (mostly copying data from existing field report). It'll be available in the staging server very soon!
We also have some of the questions for finalizing the DREF form, I'll reach out when I get the questions compiled.

**Comment by marcovvu1** [comment]
> @marcovvu1 @tovari We've nearly completed the DREF from and have started the internal testing. The testing server is available at: https://ifrc-go-feature-dref.surge.sh/
> We're still polishing some of the features (mostly copying data from existing field report). It'll be available in the staging server very soon!
> We also have some of the questions for finalizing the DREF form, I'll reach out when I get the questions compiled.

Hi! thank you very much, we have had a look and have some minors request and inputs, I compiled them in the word document atttached, I tried to be as clear as possible, but let me know if you have any question. 
[Feedback to the DREF application template.docx](https://github.com/IFRCGo/go-frontend/files/7089951/Feedback.to.the.DREF.application.template.docx)

**Comment by frozenhelium** [comment]
Hi @marcovvu1, thanks for the feedback document. We'll work on that. Meanwhile, there are few queries about the copy behaviour from existing field report.
- Should we keep a reference to which FR was linked to copy the data?
- Should we override the fields that are already filled by users?
- In case of multiple fields like country / regions, should we just add one more country / regions in dref or should we replace the existing ones?

CC: @tovari

**Comment by marcovvu1** [comment]
**- Should we keep a reference to which FR was linked to copy the data?**
Yes as both the field report and the DREF application will be refering to the same emergency
**- Should we override the fields that are already filled by users?**
No, extract from the field report should be done at the beggining before user inputs data, if the user has inputed data before connecting to a fiedl report, we will need to assume that user data is newer. @tovari recommendation is to move the field of connecting to field report to the beggining of the application.
**- In case of multiple fields like country / regions, should we just add one more country / regions in dref or should we replace the existing ones?**
it should always be aligned, so if the DREF application already has a assigned country/region, the field report should not overwrite that one

I hope this helps

CC: @tovari

**Comment by frozenhelium** [comment]
@marcovvu1 Thanks! That's much clear now. We'll move the option to link with FR to the first tab.

Another quick question, in the document, under `Description of event`, we have fields for 2 maps and upto 6 images, these 2 maps are separate from the map in `Essential information` section right?
![2021-09-03-101339](https://user-images.githubusercontent.com/4931541/131950634-82c4b3fe-fb81-4a1d-aa86-e0d58e36d543.png)

**Comment by marcovvu1** [comment]
[DREF application CLEAN.docx](https://github.com/IFRCGo/go-frontend/files/7104713/DREF.application.CLEAN.docx)
Sharing the latest version of the form as I see some track changes there still. 
Regarding the images, there will 1 map, which is requiered to submit, and then some pictures, usually not more than 5. Sometimes there are other maps (e.g. made by other agencies on the event) that they will share in the requests, but this is more part of the images of the event (so part of those 5 I mentioned above). So, 
In Essential: there will be space to add the requiered map. 
In Description of the event: Chance to add up to 6 images. (this can be photos, additional maps, infographichs)

Hope this helps.

**Comment by frozenhelium** [comment]
@marcovvu1  @tovari Available for QA on [testing server](https://ifrc-go-feature-dref.surge.sh/). We still need to decide on the Approval mechanism and the export format (Note: we have very basic export format for now)

**Comment by marcovvu1** [comment]
> @marcovvu1 @tovari Available for QA on [testing server](https://ifrc-go-feature-dref.surge.sh/). We still need to decide on the Approval mechanism and the export format (Note: we have very basic export format for now)

Dears, 

Please see attached document with a second round of feedback, same format to the one share before. Please let me know if you have any question or comment. 

Regarding the aproval process, this is what has been decided so far: We will add a funtion for users to share the form with other users. Those who have received a form, will have the oportunity to edit, and further share the the form with others. The form will be visible to only those that have recevied it. 

The current "Submit" botom, will change to "Export" and it will have the funtionality to export in a PDF version the form. 

Let me know if you have any question or comment on this.

Regarding the export, I will soon share a template on how the PDF version should look like once exported. 

Thanks, great work! 

Marco

**Comment by frozenhelium** [comment]
Hi @marcovvu1, here's the list of fields with the status of their copy from FR implementation.
| **Source field**                                     | **Target field**                   | **Copied** | **Remarks**                                 |
|------------------------------------------------------|------------------------------------|------------|---------------------------------------------|
| Request title                                        | Disaster name                      | No         | We don't have `Disaster name` field in dref |
| Country Names                                        | Affected Country                   | Yes        |                                             |
| Disaster Type ID                                     | Disaster Type ID                   | Yes        |                                             |
| FR creation date                                     | Date of GO field report            | Yes        |                                             |
| Situational overview                                 | Description of the event           | Yes        |                                             |
| Actions Taken by National SOciety Red Cross (if any) | National Society Actions           | No         | Data structure mismatch                     |
| Actions taken by any other RCRC Movement actors      | RCRC Partner NSs                   | No         | Data structure mismatch                     |
| Actions by IFRC                                      | IFRC                               | No         | Data structure mismatch                     |
| Actions Taken by Others (Governments, UN)            | Government/ UN                     | Yes        |                                             |
| National Society Contact                             | National Society Contact           | Yes        |                                             |
| IFRC Focal Point for the Emergency                   | IFRC Focal Point for the Emergency | Yes        |                                             |
| Media Contact                                        | Media Contact                      | Yes        |                                             |

**Comment by marcovvu1** [comment]
@frozenhelium 
Question. For the textboxs, is it possible that when I am over the maximum accepted characters (e.g. max 800) it tells me how many characters do I have, so I know how much above the max I am? 
![max characteres](https://user-images.githubusercontent.com/73952563/135047248-5362c9d4-d73e-4b22-b0ed-b3da2aab33cc.png)

**Comment by tovari** [comment]
Hey @frozenhelium, thanks for the pdf export function!
Two of remarks:
- can we set the file name of the pdf download to the Name of the application?
- the pdf looks nice, when it is not too text heavy. When there are a lot of text, the format breaks and texts flow out of boxes
[DREF application-Somalia-ae989266-2ff1-4eb0-bfb4-67aaf913add2.pdf](https://github.com/IFRCGo/go-frontend/files/7668770/DREF.application-Somalia-ae989266-2ff1-4eb0-bfb4-67aaf913add2.pdf)
. 
Thanks!

**Comment by anamariaescobar** [comment]
Latest and final feedback:

- [ ] Copy data from an existing field report: Rearrange, add this feature to "Essential Information" right after "Name of National Society"
- [ ] Essential Information: Disaster category, Adding a link to the IFRC Emergency framework: [https://www.ifrc.org/sites/default/files/2021-07/IFRC%20Emergency%20Response%20Framework%20-%202017.pdf ](url)
- [ ] Essential Information: Affected Country and Affected Region(s), Add location, Rename the "Add location" with "Region/Province"
- [ ] Essential Information: For imminent: Disaster Details, change "Disaster Details" to "Hazard Details"
- [ ] Essential Information: For imminent: Type of Disaster, change "Type of disaster" to "Type of Hazard"
- [ ] Timeframes: For imminent: Forecasted Date of Impact, change the box format to date.
- [ ] Description of the Event: For Imminent: "For imminent disasters, explain the different triggers to be used (if several thresholds are defined), mention the data sources that verify the risk and potential impacts to targeted communities", change to “For imminent disasters, explain the different triggers to be used (if several thresholds are defined), mention the data sources that verify the risk and potential impacts to targeted communities to For hazards, explain trigger/s used (trigger for imminent crisis, or phased triggers, for readiness/prepositioned and early action) and data sources for triggers”
- [ ] Description of the Event: For Imminent: Scopa and scale, Change the paragraph below the title to “Describe the extent this hazard will produce negative impacts on lives, livelihoods, well-being and infrastructure. Explain which people are most likely to experience the impacts of this hazard? Where do they live, and why are they vulnerable? Please explain which groups (e.g elderly, children, people with disabilities, IDPs, Refugees, etc.) are most likely to be affected? Provide historic information on how communities have been affected by the magnitude of this hazard in the past?”
- [ ] FOR Imminent: NEEDS (GAPS) IDENTIFIED, Change “NEEDS (GAPS) IDENTIFIED” to “ANTICIPATED NEEDS”
- [ ] Total Population: Can we have a control to make sure that the number is equal to the sum of the breakdown by men, women boys and girls?. And can we make it so the targeted population in “Essential Information is equal to this field?
- [ ] Objective and Rationale: Response strategy rationale: Rephrase the hint to “To address the needs of the targeted population, this DREF will aim at (please briefly describe the planned activities.”
- [ ] About Support services: Does the NS have PMER capacity? How will monitoring of the operation be organised by both NS and IFRC? If any monitoring trips are planned, clarify purpose and role to be deployed, Change to: How will this operation be monitored? Will there be IFRC monitoring visits? How will be deployed?
- [ ] About Support services: Does the NS have Communications capacity? How will communication on the operation be organised by both NS and IFRC? If any Commissions are planned, clarify purpose and role to be deployed, Change to: Please briefly explain the National Societies communication strategy for this operation. Will the IFRC be supporting with communication? What roles will be involved?
- [ ] About Support services: Are there any safety/security concerns which may impact the implementation of this operation? How will the National Society ensure the safety of the staff, volunteers and community?, Change to: Any potential risk to the implementation of this operation? What will be the mitigation measures? 
Any safety and security concerns? How will the National Society ensure the safety of the staff, volunteers and community?
- [ ] About Support services: What is the logistics capacity of the National Society? If there is procurement, will it be done by the NS or by the IFRC?, Change to: If there is procurement, will it be done by National Society or IFRC? Will it be for replenishment or for distribution? If for distribution, how long is the tendering expected to take? 
For Cash and Voucher Assistance, what is the status of the sky Financial Service Provider?
- [ ] About Support services: How many volunteers and staff involved in the response? How many will be covered through this operation?, Change to: How many staff and volunteers will be involved in this operation. Briefly describe their role.
- [ ] Planned Intervention: Showing the needs, Remove the feature that shows the information in the “needs analysis section”
- [ ] Planned Intervention: Budget Template, Change tittle to "Upload your budget summary"
- [ ] Planned Intervention: Add examples to indicators, @marcovvu1 to provide a link to the indicator list
- [ ] Tracking Data and Contacts: Please add comas for the numbers FOR THE EXPORT

CC: @tovari @frozenhelium @suraj-ram-shrestha @marcovvu1

**Comment by anamariaescobar** [comment]
Thanks @frozenhelium!

A couple of comments from the PDF export:

- [ ] The table in page 1 doesn't seem to be aligned in the right side
- [ ] Main headings should be changed to IFRC blue (Make sure we are using Montserrat as a font, the size is ok)
- [ ] All subheadings should be in IFRC red (Make sure we are using Montserrat as a font, the size is ok)
- [ ] Can we make the font on the paragraphs Open Sans 10? (I think they are 8 right now)
- [ ] Please add the picture from the Description of the event, like the map, at the end of "What happened, where and when"
- [ ] Ensure that the Current National Society Actions are reflecting the selected ones.
- [ ] Table "Previous Operations" make the answers bold
- [ ] Table "Targeted Population", make the answers (numbers) bold.

Attached the PDF export with the comments in case it is easier to follow :)
[Template comment Marilia 2212.pdf](https://github.com/IFRCGo/go-frontend/files/8023461/Template.comment.Marilia.2212.pdf)

@tovari @marcovvu1

**Comment by marcovvu1** [comment]
@frozenhelium thanks for our conversation today, as I mentioned, here is the feedback we have. 

**DREF Request form**

- [ ] In "Planned Intervention", adjust the "indicators" to reflect a list of indicators (text) and respective targets (numbers)

**DREF Request Export**

- [ ] Uploaded images, and PDF summary of the budget are not appearing in the export (This seems to be an issue of the testing server)
- [ ] Current National Society Actions - Needs to be exported similiar to "Movement Actions" like a table with the heading and the text input.
- [ ] Justify the text in the exported PDF
- [ ] Make the icons in the "Planned Intervention" section bigger, and ensure the table formatting is always aligned.
- [ ] Change the title of "Budget Overview" to "Budget Overview"

**Ops Update**

- [ ] For the first page, add the previous total allocation amount. and the total allocation make it an autimatic sum of "previous total allocation" and "additional allocation requested"
- [ ] Total operating timeframe should be an autimatic calculation of number of months between "Operations start date" and "Operations end date"
- [ ] The "Operations Start Date" needs to be automatically fielded with the Date of Approval of the DREF request 
- [ ] Remove the question on timeframe extension from the second page
- [ ] In the second page, change "Are you changing the operational strategy of the operation " to "Are you changing the operational strategy"
- [ ] Needs assessment section needs to reflec the information from the DREF request, or previous updates
- [ ] In Planned intervention, adjust the section based on the attached template 
[DREF Operations Update - Planned intervention template.docx](https://github.com/IFRCGo/go-frontend/files/8571312/DREF.Operations.Update.-.Planned.intervention.template.docx)

**For the offline template** @tovari 

- [ ] Remove the map and cover image
- [ ] Harmonise the formating and fonts based on the export template
- [ ] Check the issues around working on the document simultenously online.
[Tanzania Food insecurity.pdf](https://github.com/IFRCGo/go-frontend/files/8571318/Tanzania.Food.insecurity.pdf)

**Comment by frozenhelium** [comment]
Here's the link for the test server with latest changes: https://ifrc-go-feature-dref-operational-update.surge.sh/

**Comment by marcovvu1** [comment]
Thanks a lot Ankit! As mentioned, please see additional feedback based on the latest version you have shared. Lets discuss it tomorrow. 

**DREF Request**
- [ ] DREF Export: In Summary, change “Dref ends” for “End date of Operation”
- [ ] DREF Export: In Needs (Gaps) Identified, align the sectors’ icons with the sectors’ title in the table
- [ ] In DREF Request: In Previous Operations change “Did the NS respond?” to “Did the National Society respond?”
- [ ] In DREF Request and export: In Previous Operations below the title, add this sentence “To access lessons from previous operations, please visit the DREF Operational Learning Platform” add a hyper link for the “DREF Operational Learning Platform” section, with this link: https://go.ifrc.org/preparedness#operational-learning 
- [ ] In DREF Request and export: In Previous Operations change “Did the NS request funding from DREF?” to “Did the National Society request funding from DREF?”
- [ ] In DREF Request and export: In Previous Operations change “If yes please specify” to “If yes please specify which operations”
- [ ] In DREF Request and export: In Actions/Needs change “Movement Partners” to “Movement Partners Actions”
- [ ] In DREF Request and export: In Actions/Needs change “Other Actors” to “Other Actors Actions”
- [ ] In DREF Request and export: In Targeting Strategy change “Which groups of people will be assisted through this operation?” to “Who will be targeted through this operation?”
- [ ] In DREF Request and export: In Targeting Strategy change “What selection criteria has been used for targeting affected?” to “Explain the selection criteria for the targeted population”
- [ ] In DREF Request and export: In Targeted Population, change “Estimated Number of Displaced People” to “Estimated Number of Displaced People (if any)“
- [ ] In DREF Request and export: In “About Support Services”, change “If there is procurement, will it be done by National Society or IFRC? Will it be for replenishment or for distribution? If for distribution, how long is the tendering expected to take? For Cash and Voucher Assistance, what is the status of the sky Financial Service Provider?” to “If there is procurement, will it be done by National Society or IFRC? Will it be for replenishment or for distribution? If for distribution, how long is the tendering expected to take? For Cash and Voucher Assistance, what is the status of the Financial Service Provider?”
- [ ] In DREF Export: In About Support Services, please ensure that the titles in the export are the same that in the DREF request in GO.

 
**DREF Operational Update**
- [ ] In Export: Add to summary the “Additional allocation requested” field
- [ ] In Go and Export: In Event Details, bring back the fields in Description of the event from the DREF request form, and the field “Has anything changed in the context since the request” make it a “yes or not” toggle.
- [ ] In Go and Export: In “Current National Society Actions” add option to upload photos, title “Add photos of National Society Operation”. In the export, place the photos before the table with the National Society Actions.
- [ ] In Go: Operating timeframe is calculating the extension, not the number of months for the operation.

**Comment by marcovvu1** [comment]
@frozenhelium @anamariaescobar @tovari  Guys we finally have the funtional requierements for the DREF Final Report!!

Please see the word document attached. The Final Report is pretty much based on the existing DREF Request and Operational Update, with some rearranging of some fields, and also you will notice that some other fields do not make it to the DREF Final report. 

If you have any questions please feel free to reach out directly on Teams.

[DREF Final Report requirements.docx](https://github.com/IFRCGo/go-frontend/files/8911094/DREF.Final.Report.requirements.docx)
