### ISSUE TITLE
Covid page related updates

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1950]
The new Covid page designs are available here: https://www.sketch.com/s/2abec007-a7c8-4ec6-b679-0757fc0716c3/a/g0Zgzdd/play

The proposed new type of items:
1.	Overview tab – Links section: I think this would require a new section in the admin/emergency site as well, where the Url, the link text and the description could be added. Workaround would be to add it as a snippet, but then we should have an option to add this to the Emergency details tab.
2.	Report, documents tab – Featured documents – This propose a new section in this tab, with an option on the admin site to add documents here. It proposes to display the document thumbnail as well.
3.	Response documents – only show those boxes in which a document is published. 

The required updates:
Backend:

- [x]  Add new model for Links(Create title, URL, Desc)
- [x]  Add new model for Featured Documents(Title, file, thumbnail(also add help text for aspect ratio, desc)
- [ ]  ~~Clean up API response for response documents~~

Frontend:
- [x]  Add links to the overview tab
- [x]  Add featured documents in the report/document tabs
- [x]  Clean up UI for response documents
