### ISSUE TITLE
[PROD] User content translation issues

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2865]
We have noticed a few weird cases after the first few FRs got translated:

- [ ] translation banner appears at old emergencies as well, which are not even translated. Banner should appear only in case the content is really translated
- [ ] the styling codes may appear not only in Arabic, but in other languages as well. In this example https://go.ifrc.org/emergencies/6542#surge , the code is not displayed in the input language (French), but appears in the 3 other languages. 
- [ ] part of the text may not be translated (https://go.ifrc.org/emergencies/6542#surge): 
The French input:
![image](https://github.com/IFRCGo/go-frontend/assets/68283148/a801c8cf-3f4f-4ad7-9d94-adf619303374)
The English translation contains some French (however the same text is translated in other places of the text):
![image](https://github.com/IFRCGo/go-frontend/assets/68283148/fa2f61be-3d3d-4aaa-b5ab-96bf6ff6eb76)
The Spanish translation even contains English translations weirdly, besides the not translated French strings:
![image](https://github.com/IFRCGo/go-frontend/assets/68283148/d5fecd48-4b00-41f2-bf11-0a11eea747e2)

- [ ] This hasn't been translated to any of the languages (https://go.ifrc.org/emergencies/6508#surge)
- [ ] The user enters text not in the UI language, which doesn't allow the auto-translations: https://go.ifrc.org/emergencies/6541#surge

### Tasks
- [x] #2890
- [ ] #2891
- [ ] #2892
- [ ] #2900

**Comment by tovari** [comment]
- [ ]  Updating text on the admin page in the original language should trigger the auto translation (unless the "Skip auto translation" attribute is checked). Currently, translation update doesn't work.
