### ISSUE TITLE
Graphs show exact data as home-page but filtered by region.

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#849]
## Issue

The chart on the region does not show correct data points.

## Current Behavior
The chart on the region page show operations over the last 10 years
![image](https://user-images.githubusercontent.com/20410256/67032174-0c871d00-f0e1-11e9-9eb0-9cf60a20f4ed.png)

## Expected Behavior

The charts should show appeals and DREFs over the last year and over the past decade
![image](https://user-images.githubusercontent.com/20410256/67032204-1b6dcf80-f0e1-11e9-87bc-56f100693ddd.png)

Related Issues: #851

## Description
Key figures are referred to as [homecharts](https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/homecharts.js) in the code base

## Tasks
- [x] change the homecharts to a common component
- [x] create filter for region
- [x] add charts to region page

**Comment by LukeCaley** [comment]
User test accepted (@mmusori and @LukeCaley).  Proceed to deploy.
