### ISSUE TITLE
Update Map style

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#850]
## Issue
~~Map styles need to be updated to match mock-ups~~
EDIT:  Map styles need to be updated to match styles given in Yellow Umbrella's _Map Exploration_ document attached below and in Zeplin.

## Current Behavior
![image](https://user-images.githubusercontent.com/20410256/67036577-ddc17480-f0e9-11e9-85a3-c8ae07a9cb64.png)

## ~~Expected Behavior~~
~~the below is a screenshot from wireframes, so should not be referred to for this ticket~~
![image](https://user-images.githubusercontent.com/20410256/67036617-ef0a8100-f0e9-11e9-8a41-0479f7db8b5d.png)

## Expected Behavior
EDIT:  As per map styles in [GO_Map_Exploration.pdf](https://github.com/IFRCGo/go-frontend/files/4117148/GO_Map_Exploration.pdf)

Related Issues: #851 #830

## Description
Using the new mapbox style url: mapbox://styles/go-ifrc/cjyo249oy42oh1cphwvxyb0z5, evaluate the implications of the switch and ensure that no functionality is lost in the transition

## Tasks
- [ ] switch out the URL
- [ ] make a list of side-effects of the change
- [ ] add tasks required to make a complete transition to the new style
- [ ] apply the changes

**Comment by LukeCaley** [comment]
I believe this is a misinterpretation of the simplified wireframe design style which was used for mock-up purposes by Yellow Umbrella.  The desired colour schemes are all contained in the zeplin files @batpad

**Comment by nanometrenat** [comment]
Need to check with UX as to whether new styles have been provided.

**Comment by yellowumbrella-design** [comment]
[GO_Map_Exploration.pdf](https://github.com/IFRCGo/go-frontend/files/4117148/GO_Map_Exploration.pdf)

**Comment by nanometrenat** [comment]
**I have edited the ticket description to match the work that is required** - editing styles in Mapbox to match the YU document.

This was in 4.1, I have moved to backlog - @LukeCaley if you want it in 4.2 instead please feel free to amend.

**Comment by LukeCaley** [comment]
Thanks @nanometrenat.  Agreed that this should be parked for now - to be reviewed as part of backlog triage and planning for 4.3.

**Comment by jhenshall** [comment]
Looks like this is an old ticket that has been replaced by #1202. Closing this one but @mariam-yu, please do reopen if anything useful here.
