### ISSUE TITLE
PER: general update

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#865]
## Issue

[PER Review.pdf](https://github.com/IFRCGo/go-frontend/files/3832777/PER.Review.pdf)

## Expected behavior

The PER forms should maintain current behavior with a better backing

## Tasks
- [ ] structure form language
- [ ] set up internationalization
- [ ] create reusable form-components
- [ ] re-write HOC to manage state of various form components

**Comment by nanometrenat** [comment]
hi @batpad, assigning to you to confirm if any specific work/testing is still required under this ticket or if it can be closed now.  Thanks!
