### ISSUE TITLE
New Surge Deployments design / module

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#885]
Creating a ticket to track the Surge Deployments work.

@necoline would you be able to edit this to paste in things from the design document for this feature?

**Comment by necoline** [comment]
## Overview 
- [ ] query [google sheet](https://docs.google.com/spreadsheets/d/1CBvledFYc_uwlvHTvJE0SYS7_mPGU2L-zhrqbB4KNIA/edit?usp=sharing) into IFRC DB #906 
- [ ] create separate tables for alerts and deployments #907
- [ ]  replace ERU Readiness Cards to with iframe #908
- [ ] add surge deployments table #909

**Comment by nanometrenat** [comment]
Closing as Surge changes are on hold pending RRM integration design.  New ticket to be logged if required once those details confirmed.

Also xref https://github.com/IFRCGo/go-api/issues/464
